### ISSUE TITLE
User Activity page does not show anything but a message "Page not found"

### ISSUE THREAD

**Issue by gurjyot** [svivian/q2a-user-activity-plus#12]
The plugin is doing its job and showing links in user's profile but if we need to add a page of user's activity from admin>pages then that page shows nothing except a message "Page not found".

**Comment by svivian** [comment]
Can you explain what you mean by "add a page of user's activity from admin>pages"? You shouldn't need to add any page, it works without that.

Also, since this functionality is now in core Q2A I'm probably not going to develop this plugin any more.

**Comment by gurjyot** [comment]
If you are not gonna develop this plugin in future then its ok, no need to solve this issue... :)
