### ISSUE TITLE
sql_mode=only_full_group_by

### ISSUE THREAD

**Issue by ESeufert** [svivian/q2a-user-activity-plus#14]
For anyone getting this MySQL error on users' question and answer pages:

`1140: In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'quantmar.u.userid'; this is incompatible with sql_mode=only_full_group_by`

The cause is that you have the only_full_group_by setting turned on. You can fix this in lines 215 and 230 in the qa-user-activity.php file by adding `GROUP BY u.userid` to the end of the `$sql_count` variable.

**Comment by svivian** [comment]
This plugin is no longer active. The functionality has been in core Q2A for several years now.
